In [1]:
import os

In [2]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Mounted at /gdrive
/gdrive


In [3]:
os.getcwd()

'/gdrive'

In [ ]:
os.chdir(f'{os.getcwd()}\\Desktop\\colab_local')

In [3]:
# 만약에 파일 없으면 !mkdir "KSLProject"

%cd 'MyDrive'
%cd 'KSLProject'
# %cd 'hmdb51'

/gdrive/MyDrive
/gdrive/MyDrive/KSLProject


In [ ]:
!wget http://serre-lab.clps.brown.edu/wp-content/uploads/2013/10/hmdb51_org.rar

--2021-05-19 18:22:59--  http://serre-lab.clps.brown.edu/wp-content/uploads/2013/10/hmdb51_org.rar
Resolving serre-lab.clps.brown.edu (serre-lab.clps.brown.edu)... 128.148.254.114
Connecting to serre-lab.clps.brown.edu (serre-lab.clps.brown.edu)|128.148.254.114|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://serre-lab.clps.brown.edu/wp-content/uploads/2013/10/hmdb51_org.rar [following]
--2021-05-19 18:22:59--  https://serre-lab.clps.brown.edu/wp-content/uploads/2013/10/hmdb51_org.rar
Connecting to serre-lab.clps.brown.edu (serre-lab.clps.brown.edu)|128.148.254.114|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2124008126 (2.0G)
Saving to: ‘hmdb51_org.rar’

hmdb51_org.rar      100%[===================>]   1.98G  19.8MB/s    in 74s     

2021-05-19 18:24:13 (27.4 MB/s) - ‘hmdb51_org.rar’ saved [2124008126/2124008126]



In [ ]:
# %cd "../"
%ls

문서/  conv_lstm_2d.h5  hmdb51/  hmdb51_org.rar  model.png


In [ ]:
#unzip rar file
!unrar x ../hmdb51_org.rar

In [ ]:
ls

In [ ]:
ls

In [ ]:
!unrar x for i in brush_hair.rar

In [ ]:
file_list = []
file_list = os.listdir(os.getcwd())
print(file_list)

In [ ]:
cur_path = os.getcwd() 
cur_path

In [ ]:
# for x in file_list:
#   !unrar x cur_path
!unrar x for i in file_list

In [4]:
import cv2
import os
import numpy as np
import matplotlib.pyplot as plt

In [5]:
frames = 15
Width = 256
Height = 256

In [6]:
#비디오명과 레이블 짝을 가져온다.
def load_video_names(path):

  videos = []
  labels = []
  for category in os.listdir(path): #root 폴더의 각 하위폴더들은 클래스이름이기 때문에 이것을 category로 저장
    for video in os.listdir(path+"/"+category): #인자로 받은 경로(path)와 클래스명을 붙여서 각각의 비디오별
      videos.append(path+"/"+category+"/"+video) #비디오의 경로명을 videos에 넣는다.
      labels.append(category) #category명 즉 폴더명이 클래스이므로 label로 넣는다.
  return np.array(videos), np.array(labels) #이것들을 array값으로 반환한다.

#프레임 전처리 함수 preprocess()
def preprocess(frame):
  frame = cv2.resize(frame, (Width, Height))
  # 프레임 픽셀 -1에서 1 범위로 정규화(normalization)
  frame = frame - 127.5 # RGB값 : 255/2 - 0.5
  frame = frame / 127.5
  return frame

#비디오 불러오기 함수 load_video()
def load_video(video_path):
  video_frames = []
  cap = cv2.VideoCapture(video_path) #비디오 경로를 입력하여 cap 인자로 cv2비디오캡처를 실행
  while True:
    ret, frame = cap.read() #비디오의 캡처를 읽어오고
    if ret == True: #실행되는 동안
      video_frames.append(preprocess(frame)) #전처리된 프레임을 video_frames 리스트에 추가
    else:
      break
  cap.release()
  video_frames = select_frames(video_frames) #비디오 프레임을 select frames()에 처리시킨다.
  if len(video_frames) != frames:
    print('short_video ',video_path, len(video_frames))
    
  return np.array(video_frames)


def select_frames(video_frames): # video_frames인자는 전처리한 프레임들을 저장한 리스트 형태
  selected_frames = []
  if len(video_frames) > frames: # 전체 비디오 프레임 수가 지정한 프레임 (15)보다 큰 동안
    fn = len(video_frames)//frames # 전체 프레임수를 지정프레임수로 나누고 나머지를 버린 몫을 fn으로 산정 ( //연산자 : 나눈 값에서 소수점을 버린 정수값을 취함)
    # 예를들어 가져온 비디오의 전체프레임이 119프레임이라할때 15로 나누면 7.93333 이고 여기에 나머지를 버리면 7이라는 값이 나옴
    # 즉, 전체프레임에서 fn만큼의 간격을 두고 15개의 프레임을 취하기 위해서 이 함수가 존재하는것
    f_num = 0 # 현재 선택된 프레임의 수 
    for f in video_frames: # 각각의 비디오 프레임 값(array배열 값)에 대해서 f로 지정
      if len(selected_frames) < frames: # 만약 선택된 프레임의 수가 전체 할당하고자하는 프레임 수(15)보다 작은 상태라면
        if f_num % fn == 0: # f_num이 fn의 배수가 될 때마다(나누어 떨어질 때마다) 해당 프레임의 위치를 표시
          selected_frames.append(f) # selected_frames에 프레임을 추가
          #즉 fn이 7값이면 7프레임 단위로 끊어서 전체 비디오의 프레임을 가져온다. 7 * 15 = 105, 7 * 16 = 
      f_num += 1 # 선택된 프레임 수 1 증가
  else:
    selected_frames = video_frames #만약 전체 비디오의 프레임 수가 지정한 프레임(15)보다 작은경우 그냥 그프레임 자체를 데이터로 설정
  return selected_frames  #즉, 전체 프레임을 설정한 frames=15라는 값에 의해 15개의 프레임만 선택적으로 균일한 간격을 이루어 선택적으로 취하는 코드

# X, y = create_dataset(videos, encoded_labels, selected_indexes)
def create_dataset(videos, labels, indx):
  """
  이 함수는 배치사이즈 크기만큼의 비디오를 불러오는 데 사용. load_video로 우선 단일 비디오를 불러오는 것을 매개로 함
  파라미터
  videos : 모든 비디오의 경로값
  labels : 비디오들의 아웃풋 클래스
  indx : 배치로 사용되는 비디오들의 인덱스
  """
  X = []
  y = []
  for video, label in zip(videos[indx], labels[indx]):
    X.append(load_video(video))
    y.append(label)

  return np.array(X), np.array(y)



In [7]:
videos, labels = load_video_names('./temp_data') #path ./hmdb51 내에 있는 각각의 클래스 폴더들의 비디오 이름들을 가져와 videos와 labels로 할당한다.
samples = len(videos)
# videos[0][-3:]

In [8]:
samples
# print(labels)

140

In [9]:
#모든 비디오의 label값이 중복으로 나타나는 것을
#np.unique()함수를 이용하여 같은값의 중복을 없앰
classes = len(np.unique(labels)) 


In [36]:
classes

7

In [ ]:
# print(np.unique(labels, return_counts=True))


In [10]:
#비디오가 제대로 불러와졌는지 확인

labels_counts = np.unique(labels, return_counts=True) #각 레이블이 몇 개씩 존재하는지 반환하는 인자 return_counts
print(labels_counts)
print(np.shape(labels_counts))
for l, n in zip(labels_counts[0], labels_counts[1]): #l과 n에 각각 첫번째 배열의 요소와 두번째 배열의 요소를 대응
# l값은 분류 레이블의 이름이 저장되어있고 n값은 해당 레이블의 개수가 저장되어있음
 print(l,n)

(array(['등', '무릎', '발', '발가락', '발목', '발작', '복부'],
      dtype='<U8'), array([20, 20, 20, 20, 20, 20, 20]))
(2, 7)
등 20
무릎 20
발 20
발가락 20
발목 20
발작 20
복부 20


In [11]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

le = LabelEncoder() #LabelEncoder() 객체를 통해 문자로 이루어진 클래스를 숫자 형태로 적용
le.fit(np.unique(labels)) #label의 유니크 값을 le.fit()함수에 넣어 고유값을 fitting 시킴

encoded_labels = le.transform(labels) #fit을 시켜주지 않으면 다음과 같은 에러메세지를 출력 
# This LabelEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
# print(encoded_labels) # 결과값 : [63 63 63 ... 2  2  2]
encoded_labels = np.reshape(encoded_labels, (-1,1)) # 하나의 row에 값들을 나열 (수평축의 크기를 1로 해서 1개의 요소가 들어가면 다음 열로 넘어감)
# print(encoded_labels)

encoder = OneHotEncoder()
encoder.fit(encoded_labels) # 나열된 레이블 값들을 원핫 인코더에 적용시키기 위해 .fit()실행
encoded_labels = encoder.transform(encoded_labels)

print(encoded_labels)

  (0, 2)	1.0
  (1, 2)	1.0
  (2, 2)	1.0
  (3, 2)	1.0
  (4, 2)	1.0
  (5, 2)	1.0
  (6, 2)	1.0
  (7, 2)	1.0
  (8, 2)	1.0
  (9, 2)	1.0
  (10, 2)	1.0
  (11, 2)	1.0
  (12, 2)	1.0
  (13, 2)	1.0
  (14, 2)	1.0
  (15, 2)	1.0
  (16, 2)	1.0
  (17, 2)	1.0
  (18, 2)	1.0
  (19, 2)	1.0
  (20, 3)	1.0
  (21, 3)	1.0
  (22, 3)	1.0
  (23, 3)	1.0
  (24, 3)	1.0
  :	:
  (115, 0)	1.0
  (116, 0)	1.0
  (117, 0)	1.0
  (118, 0)	1.0
  (119, 0)	1.0
  (120, 1)	1.0
  (121, 1)	1.0
  (122, 1)	1.0
  (123, 1)	1.0
  (124, 1)	1.0
  (125, 1)	1.0
  (126, 1)	1.0
  (127, 1)	1.0
  (128, 1)	1.0
  (129, 1)	1.0
  (130, 1)	1.0
  (131, 1)	1.0
  (132, 1)	1.0
  (133, 1)	1.0
  (134, 1)	1.0
  (135, 1)	1.0
  (136, 1)	1.0
  (137, 1)	1.0
  (138, 1)	1.0
  (139, 1)	1.0


In [12]:
# 인코딩 레이블 값을 array값으로 covert
encoded_labels = encoded_labels.toarray()
print(encoded_labels)
#어쨋든 데이터로 들어가야 하는 레이블 값은 다음과 같은 값이어야 함

[[0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.

In [13]:
np.shape(encoded_labels) #(영상 개수, 클래스 개수)

(140, 7)

In [14]:
from sklearn.model_selection import train_test_split
seed = 0
X_train , X_test, Y_train, Y_test = train_test_split(videos, encoded_labels, test_size=0.3, random_state=seed)

train_samples = len(X_train)
test_samples = len(X_test)

In [15]:
print("원본 동영상 X : ", np.shape(videos))
print("훈련 동영상 X_train : {0}, 테스트 동영상 X_test: {1}" .format(np.shape(X_train), np.shape(X_test)))

print("원본 레이블 Y : ", np.shape(encoded_labels))
print("훈련 레이블 Y_train : {0}, 테스트 레이블 Y_test : {1}" .format(np.shape(Y_train), np.shape(Y_test)))

원본 동영상 X :  (140,)
훈련 동영상 X_train : (98,), 테스트 동영상 X_test: (42,)
원본 레이블 Y :  (140, 7)
훈련 레이블 Y_train : (98, 7), 테스트 레이블 Y_test : (42, 7)


In [17]:
#케라스 모델 생성
from keras.models import Input, Model
from keras.layers import TimeDistributed, LSTM
from keras.layers import ConvLSTM2D
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, LeakyReLU, BatchNormalization
from keras.layers import Dense, Flatten, GlobalMaxPooling2D
from keras.layers import MaxPooling3D
from keras.layers import concatenate
from keras.optimizers import Adam

In [ ]:
# import tensorflow as tf
# import numpy as np
# import matplotlib.pyplot as plt

In [ ]:
tf.__version__

'2.5.0'

In [18]:
'''
feature extraction을 하기위해 사용하는 residual block
한개의 CNN 레이어와 leaky relu가 action을 파악하는 펑션으로 포함되어있음
'''
def res_block(model, filters):
  '''
  feature extraction 하기 위한 residual block
  1개의 CNN 레이어와 leaky relu action 함수 포함
  '''

  #model = TimeDistributed(Conv2D(filters=filters,
  #kernel_size=3, padding='same'))(model)
  start_block = model
  model = Conv2D(filters=filters, kernel_size=3, padding='same')(model)
  model = BatchNormalization(momentum=0.9)(model)
  model = LeakyReLU(0.2)(model)
  return concatenate([start_block, model])

def create_model():
  '''
  전체 모델 구조를 설정, ConvLSTM2D 레이어를 구성
  이를 통해 비디오의 spatial(공간적)특성과 temporal(일시성, 시간성)특성을 캐치

  '''
  input_layer = Input(shape=(frames, Width,Height,3))

  model = ConvLSTM2D(32, 3 , padding='same', return_sequences=False)(input_layer)
  model = BatchNormalization(momentum=0.9)(model)
  model = LeakyReLU(0.2)(model)

  filters = 64 #필터 개수 설정

  for _ in range(6):
    model = res_block(model, filters)
    try:
      model = MaxPooling3D((2,2,2))(model)
    except:
      model = MaxPooling2D((2,2))(model)
    if filters < 512:
      filters *= 2

  #model = TimeDistributed(Conv2D(filters, 3 , padding='same'))(model)
  #model = TimeDistributed(GlobalMaxPooling2D())(model)
  model = Flatten()(model)

  # 출력층
  model = Dense(classes, activation='softmax')(model)
  model = Model(input_layer , model)
  model.compile(optimizer=Adam(learning_rate=1e-4),
                loss='categorical_crossentropy',
                metrics=['accuracy'])
  return model

In [19]:
classifier = create_model()

In [21]:
classifier.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 15, 256, 256 0                                            
__________________________________________________________________________________________________
conv_lst_m2d (ConvLSTM2D)       (None, 256, 256, 32) 40448       input_1[0][0]                    
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 256, 256, 32) 128         conv_lst_m2d[0][0]               
__________________________________________________________________________________________________
leaky_re_lu (LeakyReLU)         (None, 256, 256, 32) 0           batch_normalization[0][0]        
______________________________________________________________________________________________

In [22]:
# 모델 그래프 생성
from keras.utils import plot_model
plot_model(classifier)


ImportError: ignored

In [22]:
#모델 저장할 경로 설정
model_name = './conv_lstm_2d.h5'

In [23]:
# pre-train된 가중치를 불러오기
try:
  classifier.load_weights(model_name)
except:
  pass

In [24]:
def set_batches(samples, batch_size=4):
  batch_size = batch_size

  if samples//batch_size < samples/batch_size: #소수점 버리고 +1 
    batches = (samples//batch_size)+1 #train_samples 기준 총 배치사이즈 : 888/4 = 222
  else: # 소수점 없이 나누어 떨어지는 경우
    batches = samples//batch_size 

  return batches

In [29]:
batch_size = 4 #batch 사이즈 설정
# # total batches
# # 기존 samples를 train_samples로 교체

# # samples//batch_size = 1289 // 4  = 322 < 1289/4 = 322.25  9
# if train_samples//batch_size < train_samples/batch_size: # 
#   batches = (train_samples//batch_size)+1 #train_samples 기준 총 배치사이즈 : 888/4 = 222
# else:
#   batches = train_samples//batch_size 

#model.fit() 대신에 train_on_batch()를 사용
# 장점
# 특정 주기에만 가중치를 업데이트 , 가중치 업데이트로 인한 학습시간을 단축할 수 있다.
# 실시간 batch의 추적을 통해서 중간 저장이 가능하다.
# 또한 각 배치 사이에서 값의 조정이 가능하다.
 
# X_eval = []
# Y_eval = []



for e in range(100): #에폭 수 
  score = []
  test_accuracy = 0
  # index = list(range(samples))
  index = list(range(train_samples))                                                  ####################### 수정한 부분
  np.random.shuffle(index) # 인덱스를 저장한 배열을 무작위 순서로 설정
  accuracy = 0
  
  batches_for_train = set_batches(train_samples, batch_size)                                                              ###################### 2차 수정

  for batch in range(batches_for_train): # 0 ~ 222
    bs = batch*batch_size # MINIMUM = 0 * 4 = 0 ~ MAXIMUM = (222) * 4 =  # 0 ~ 888
    be = bs+batch_size # MIN = 0 + 4 = 4 ~ MAX = 888 + 4 = 892
    selected_indexes = index[bs:be] #index [0:888, 4:892]

    # X, y = create_dataset(videos, encoded_labels, selected_indexes) 
    # 기존의 위 코드에서 train / test로 분리시켰기 때문에 videos, encoded_labels 대신에 X_train, Y_train 값을 부여
    X, y = create_dataset(X_train, Y_train, selected_indexes)
    
    results = classifier.train_on_batch(X,y)
    print('\r', batch, '/', batches_for_train, ' : ', results[0], results[1], end='')
    accuracy += results[1]
    if batch%15 == 0:
      classifier.save_weights(model_name)

  print('\r> ',e,', Train Accuracy = ', accuracy/batches_for_train)

  index2 = list(range(test_samples))
  np.random.shuffle(index2)
  batches_for_test = set_batches(test_samples, batch_size) # = 11
  for batch in range(batches_for_test):
    bs = batches_for_test*batch_size #11 *4 = 44
    be = bs+batch_size
    selected_indexes2 = index2[bs:be]
    X_test, Y_test = create_dataset(X_test, Y_test, selected_indexes2)
    test_results = classifier.evaluate(X_test, Y_test, batch_size = batch_size, verbose=0) # [0] loss [1] accuracy
    print(test_results)
    # test_accuracy += test_results[1]

  print("\n Test Accuracy :", test_accuracy/batches_for_test) # 정확성 평가 부분을 추가 ######################### 수정한 부분
  classifier.save_weights(model_name)

>  0 , Train Accuracy =  0.99
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]

 Test Accuracy : 0.0
>  1 , Train Accuracy =  0.95
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]

 Test Accuracy : 0.0
>  2 , Train Accuracy =  0.98
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]

 Test Accuracy : 0.0
>  3 , Train Accuracy =  0.97
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]

 Test Accuracy : 0.0
>  4 , Train Accuracy =  0.97
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]

 Test Accuracy : 0.0
 14 / 25  :  9.040936856763437e-05 1.0

KeyboardInterrupt: ignored